---
- name: Install Nginx
  apt: pkg=nginx state=latest

- name: Change default nginx site
  template: src=default.j2 dest=/etc/nginx/sites-enabled/default
  notify: restart nginx

- name: Add xhgui nginx site
  template: src=xhgui.j2 dest=/etc/nginx/sites-enabled/xhgui
  notify: restart nginx

- shell: grep ^processor /proc/cpuinfo | wc -l
  register: processor_count
  ignore_errors: True

- name: Copy over NGINX Config
  template: src=conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
