---
- name: Output the current host
  hosts: all
  remote_user: root
  roles:
    - sethostname

- name: All Hosts - Update Apt
  hosts: all
  remote_user: root
  sudo: yes
  roles:
    - aptupdate

- name: Vagrant - Install NGINX, Memcache, Beanstalk, GeoIP, MySQL and PHP-FPM
  hosts: vagrant
  become: true
  roles:
    - nginx
    - php-fpm
    - mysql
    - gzip
    - memcache
    - beanstalk
    - geoip
    - debug-file
    - mongo
    - composer
    - xhgui
